<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            [
                'name' => 'Specialized Allez E5 2020 Road Bike',
                'price' => '16250',
                'image1' => 'img/products/folder1/1.jpg',
                'image2' => 'img/products/folder1/2.jpg',
                'image3' => 'img/products/folder1/3.jpg',
                'image4' => 'img/products/folder1/4.jpg',
                'brake__type_id' => 1,
                'brand_id' => 1,
                'category_id' => 2,
                'discipline_id' => 1,
                'drivetrain_brand_id'=> 1,
                'drivetrain_groupset_id'=> 1,
                'frame_material_id'=> 3,
                'gear_type_id'=> 1,
                'model_family_id'=> 1,
                'size_id'=> 4,
            ],
            [
                'name' => 'Cannondale CAAD Optimo Sora 2020 Road Bike',
                'price' => '17250',
                'image1' => 'img/products/folder2/1.jpg',
                'image2' => 'img/products/folder2/2.jpg',
                'image3' => 'img/products/folder2/3.jpg',
                'image4' => 'img/products/folder2/4.jpg',
                'brake__type_id' => 2,
                'brand_id' => 2,
                'category_id' => 8,
                'discipline_id' => 2,
                'drivetrain_brand_id'=> 2,
                'drivetrain_groupset_id'=> 2,
                'frame_material_id'=> 1,
                'gear_type_id'=> 2,
                'model_family_id'=> 2,
                'model_year_id'=> 1,
                'size_id'=> 5,
            ],
            [
                'name' => 'Cannondale CAAD Optimo Tiagra 2020 Road Bike',
                'price' => '17250',
                'image1' => 'img/products/folder3/1.jpg',
                'image2' => 'img/products/folder3/2.jpg',
                'image3' => 'img/products/folder3/3.jpg',
                'image4' => 'img/products/folder3/4.jpg',
                'brake__type_id' => 3,
                'brand_id' => 3,
                'category_id' => 1,
                'discipline_id' => 3,
                'drivetrain_brand_id'=> 1,
                'drivetrain_groupset_id'=> 3,
                'frame_material_id'=> 2,
                'gear_type_id'=> 1,
                'model_family_id'=> 3,
                'model_year_id'=> 2,
                'size_id'=> 6,
            ],
            [
                'name' => 'Bianchi Via Nirone Claris 2020 Road Bike',
                'price' => '15220',
                'image1' => 'img/products/folder4/1.jpg',
                'brake__type_id' => 1,
                'brand_id' => 4,
                'category_id' => 2,
                'discipline_id' => 4,
                'drivetrain_brand_id'=> 2,
                'drivetrain_groupset_id'=> 4,
                'frame_material_id'=> 3,
                'gear_type_id'=> 2,
                'model_family_id'=> 4,
                'model_year_id'=> 3,
                'size_id'=> 1,
            ],
            [
                'name' => 'Pinnacle Dolomite Limited Edition 2020 Road Bike',
                'price' => '13250',
                'image1' => 'img/products/folder5/1.jpg',
                'image2' => 'img/products/folder5/2.jpg',
                'brake__type_id' => 2,
                'brand_id' => 5,
                'category_id' => 3,
                'discipline_id' => 5,
                'drivetrain_brand_id'=> 1,
                'drivetrain_groupset_id'=> 5,
                'frame_material_id'=> 2,
                'gear_type_id'=> 1,
                'model_family_id'=> 5,
                'model_year_id'=> 1,
                'size_id'=> 2,
            ],
            [
                'name' => 'Pinnacle Laterite 1 2020 Road Bike',
                'price' => '16750',
                'image1' => 'img/products/folder6/1.jpg',
                'image2' => 'img/products/folder6/2.jpg',
                'brake__type_id' => 3,
                'brand_id' => 6,
                'category_id' => 4,
                'discipline_id' => 1,
                'drivetrain_brand_id'=> 2,
                'drivetrain_groupset_id'=> 6,
                'frame_material_id'=> 1,
                'gear_type_id'=> 2,
                'model_family_id'=> 6,
                'model_year_id'=> 2,
                'size_id'=> 3,
            ],
            [
                'name' => 'Specialized Allez E5 Elite 2020 Road Bike',
                'price' => '11750',
                'image1' => 'img/products/folder7/1.jpg',
                'image2' => 'img/products/folder7/2.jpg',
                'image3' => 'img/products/folder7/3.jpg',
                'image4' => 'img/products/folder7/4.jpg',
                'brake__type_id' => 1,
                'brand_id' => 7,
                'category_id' => 5,
                'discipline_id' => 2,
                'drivetrain_brand_id'=> 1,
                'drivetrain_groupset_id'=> 7,
                'frame_material_id'=> 2,
                'gear_type_id'=> 1,
                'model_family_id'=> 7,
                'model_year_id'=> 3,
                'size_id'=> 4,
            ],
            [
                'name' => 'Cannondale Synapse Neo 1 2020 Electric Road Bike',
                'price' => '28750',
                'image1' => 'img/products/folder8/1.jpg',
                'image2' => 'img/products/folder8/1.jpg',
                'image3' => 'img/products/folder8/1.jpg',
                'image4' => 'img/products/folder8/1.jpg',
                'brake__type_id' => 2,
                'brand_id' => 8,
                'category_id' => 6,
                'discipline_id' => 3,
                'drivetrain_brand_id'=> 2,
                'drivetrain_groupset_id'=> 8,
                'frame_material_id'=> 3,
                'gear_type_id'=> 2,
                'model_family_id'=> 8,
                'model_year_id'=> 1,
                'size_id'=> 5,
            ],
            [
                'name' => 'Specialized Diverge E5 Comp 2020 Road Bike',
                'price' => '18750',
                'image1' => 'img/products/folder9/1.jpg',
                'image2' => 'img/products/folder9/2.jpg',
                'image3' => 'img/products/folder9/3.jpg',
                'image4' => 'img/products/folder9/4.jpg',
                'brake__type_id' => 3,
                'brand_id' => 9,
                'category_id' => 7,
                'discipline_id' => 4,
                'drivetrain_brand_id'=> 1,
                'drivetrain_groupset_id'=> 1,
                'frame_material_id'=> 1,
                'gear_type_id'=> 1,
                'model_family_id'=> 9,
                'model_year_id'=> 2,
                'size_id'=> 6,
            ],
            [
                'name' => '3T Strada Team Red eTAP 2019 Road Bike',
                'price' => '29750',
                'image1' => 'img/products/folder10/1.jpg',
                'image2' => 'img/products/folder10/1.jpg',
                'image3' => 'img/products/folder10/1.jpg',
                'image4' => 'img/products/folder10/1.jpg',
                'brake__type_id' => 1,
                'brand_id' => 10,
                'category_id' => 8,
                'discipline_id' => 5,
                'drivetrain_brand_id'=> 2,
                'drivetrain_groupset_id'=> 2,
                'frame_material_id'=> 2,
                'gear_type_id'=> 2,
                'model_family_id'=> 10,
                'model_year_id'=> 3,
                'size_id'=> 7,
            ],
        ]);
    }
}
